version: "3"

services:
  auctioneer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - ENV=dev
      - PORT=8080
      - AUCTIONEER_HOST=http://localhost:8080
    networks:
      - auctioneer_network

  bidder_1:
    build:
      context: ./cmd/bidder
      dockerfile: Dockerfile
    command: ./bidder -port=8000 -name=bidderOne -delay=5
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - auctioneer
    environment:
      - ENV=dev
      - AUCTIONEER_HOST=http://auctioneer:8080
      - BIDDER_HOST=bidder_1
    links:
      - "auctioneer"
    networks:
      - auctioneer_network

  bidder_2:
    build:
      context: ./cmd/bidder
      dockerfile: Dockerfile
    command: ./bidder -port=8001 -name=bidderTwo -delay=10
    ports:
      - "8001:8001"
    restart: unless-stopped
    depends_on:
      - auctioneer
    environment:
      - ENV=dev
      - AUCTIONEER_HOST=http://auctioneer:8080
      - BIDDER_HOST=bidder_2
    links:
      - "auctioneer"
    networks:
      - auctioneer_network

  bidder_3:
    build:
      context: ./cmd/bidder
      dockerfile: Dockerfile
    command: ./bidder -port=8002 -name=bidderThree -delay=15
    ports:
      - "8002:8002"
    restart: unless-stopped
    depends_on:
      - auctioneer
    environment:
      - ENV=dev
      - AUCTIONEER_HOST=http://auctioneer:8080
      - BIDDER_HOST=bidder_3
    links:
      - "auctioneer"
    networks:
      - auctioneer_network

networks:
  auctioneer_network:
